use_small_heuristics = "Max"
merge_imports = true
max_width = 100
comment_width = 100
wrap_comments = true
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
fn_single_line = true
format_strings = true
reorder_impl_items = true
#report_todo = "Always"
#report_fixme = "Always"
use_field_init_shorthand = true
use_try_shorthand = true
#format_code_in_doc_comments = true
normalize_doc_attributes = true
