# https://rust-lang.github.io/rustfmt/?version=master

comment_width = 100
condense_wildcard_suffixes = true
fn_args_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
max_width = 100
merge_derives = true
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
